name: crv-website
static_sites:
  - name: web
    github:
      repo: zentratek/crv-website
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    output_dir: /out
